targets:
  $default:
    builders:
      objectbox_registry|entity_registry:
        enabled: true

builders:
  entity_registry:
    import: "package:objectbox_registry/objectbox_registry.dart"
    builder_factories: ["entityRegistryBuilder"]
    build_extensions: {"$lib$": ["generated/entity_registry.g.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
    runs_before: [
      "json_serializable|json_serializable",
      "riverpod_generator|riverpod_generator",
      "freezed|freezed"
    ]